### ISSUE TITLE
Top line nav highlighting bug

### ISSUE THREAD

**Issue by pglowacky** [livepeer/livepeer-studio-docs#140]
Highlighting the name of sections is currently inconsistent and can be disorienting. Only one top-line item should be highlighted in blue at any time. 

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/79172645/178985523-967db7f1-b393-4642-8b98-5529bd858c73.png">

**Comment by hnjolles1** [comment]
@pglowacky this is a duplicate with this -- Navigation Guides -- make an Index Page for Guides and change the Quickstart to something so the navigation doesn't duplicate #129 -- any chance @adamsoffer you can take a look at the navigation in Docusaurus config to see if there is a better way to do this?
