### ISSUE TITLE
On Demand Core Concepts missing storing on IPFS

### ISSUE THREAD

**Issue by pglowacky** [livepeer/livepeer-studio-docs#142]
Under capabilities, On Demand Core Concepts needs to list Export to IPFS with the description, "By default, all assets are stored on Google Cloud. Using the the `export` end point, assets can be stored on IPFS"

**Comment by hnjolles1** [comment]
@pglowacky do we want to mention 3rd party vendors -- for example, in other parts of the documentation we removed Youtube, and things like that...

**Comment by hnjolles1** [comment]
@pglowacky since the export is going to be removed , are you sure you want to keep this? 
See https://github.com/livepeer/livepeer-studio-docs/pull/146
