### ISSUE TITLE
Playback a Video

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-studio-docs#181]
- Should include instructions on how to embed

**Comment by pglowacky** [comment]
@ichung08 @adamsoffer Head's up that I moved this to to get done this week so it coincides with the player being ready. Docs should swap out the lvpr.tv iframe.

**Comment by ichung08** [comment]
show how to use the Livepeer Player in a react application. Should work for both live and demand video playback. https://livepeerjs.org/examples/video-player#step-2-play-video
