### ISSUE TITLE
Change order of Live and On Demand 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/livepeer-studio-docs#192]
Can we change the order in the docs to have On Demand come first? We're going to be leading with On Demand as the primary way to use Studio, so it should be the very top of any list that showcases our products. 

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/9b11b8b4-27e4-40d7-9b49-a91512d816f8)

**Comment by ichung08** [comment]
Issue seems to have been resolved

![CleanShot 2022-09-08 at 00 10 39](https://user-images.githubusercontent.com/69920967/189058085-7440a1d9-480d-4feb-b968-976151897578.png)
