### ISSUE TITLE
Put Sample Application in /reference/examples

### ISSUE THREAD

**Issue by pglowacky** [livepeer/livepeer-studio-docs#195]
We need to include Shih Yu's sample application in the "Examples" section of the guide. 

https://studio-sample-app.vercel.app/onDemand link to sample app

https://github.com/livepeer/studio-sample-app link to Github repo

@Shih-Yu Can you provide a short description like what is provided at https://docs.livepeer.studio/reference/examples?

**Comment by Shih-Yu** [comment]
> This sample application demonstrates the capabilities of what to expect when building with the On Demand feature. When building a project with On Demand, there are several approaches to take, whether more in-depth using the API or plug and play with the SDK. 

Open to suggestions/edits 🙂
