### ISSUE TITLE
Document Access Control

### ISSUE THREAD

**Issue by victorges** [livepeer/livepeer-studio-docs#206]
Add the following to: https://docs.livepeer.studio/category/api
- [x] #223
- [x] #222
- [x] #225
- [x] #226
- [x] #227

**Comment by victorges** [comment]
internal technical docs: https://www.notion.so/livepeer/Signing-Keys-for-Access-Control-8879f96a5aaf409eb4042acc281f5caa

**Comment by ichung08** [comment]
As a first step want to catalog the list of the api endpoints in that notion page (post, get, update, delete) and then create a to do list based on them in that github issue?

**Comment by pglowacky** [comment]
Needs to include this change before merging:

> FTR we are changing the returned private key from the signing key API as a base64 encoded pem instead of a pem, so devs won't have to deal with line breaks. They will however need to decode the string to use it to sign JWTs. This is the same behavior of Mux. The doc need to be changed accordingly

https://github.com/livepeer/studio/pull/1419
