### ISSUE TITLE
Improve Playback a Video Guide

### ISSUE THREAD

**Issue by ichung08** [livepeer/livepeer-studio-docs#233]
based off of https://docs.mux.com/guides/video/play-your-videos

**Comment by pglowacky** [comment]
Needs to include this warning: https://app.zenhub.com/workspaces/studio-62e817e78dcba15ddb23d5ad/issues/livepeer/livepeer-studio-docs/208

**Comment by suhailkakar** [comment]
Completed #246

**Comment by victorges** [comment]
Need to merge this one to finish this: https://github.com/livepeer/livepeer-studio-docs/pull/246
